spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board_group3_clone2?serverTimezone=Asia/Seoul
    username: root
    password: mypassword

server:
  port: 8081


# OpenWeatherAPI 설정
openweathermap.api.key: 248272caccbe78177c150490bf086679